<a href="https://colab.research.google.com/github/Eddychege/alx_python/blob/main/HCIA_AI_CERTIFICATION_DAILY_EXERCISE_PYTHON_BASICS_EddieChege_Group2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy

In [41]:
print(numpy.version.version)

2.0.2


In [42]:
import pandas as pd

In [43]:
print(pd.__version__)

2.2.2


In [44]:
print('Hello HCIA-Huawei Team')

Hello HCIA-Huawei Team


In [45]:
a = 2
b = 3
print(a+b)

5


In [46]:
x=(2,)

In [47]:
y=(2,3,4,5,6)
for i in y:
    print(i)

2
3
4
5
6


In [48]:
x = [1,2,3,4,5]
y = [11,12,13,14,15]
z=(21,22,23,24,25)
for i,j,k in zip(x,y,z):
    print(i,j,k)

print(3*x)
print(x+y)
# print(x-y)
print(x[1])
print(x[0])
print(x[-1])

1 11 21
2 12 22
3 13 23
4 14 24
5 15 25
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 11, 12, 13, 14, 15]
2
1
5


In [49]:
my_dict = {}
print(my_dict)
print(type(my_dict))

{}
<class 'dict'>


In [50]:
my_dict = { 'name':'Reagan','phone': '+254722222333'}
print(my_dict)

{'name': 'Reagan', 'phone': '+254722222333'}


In [51]:
HCIA_AIdict = {}
HCIA_AIdict = {'Philip_Oyier':'kisumu','Peter_Kiguru':'Kiambu','Susan_Neema':'Nairobi','Mary_Njue':'Kiambu','Eddie_Chege':'Kiambu'}
print(HCIA_AIdict.items())
print(HCIA_AIdict.keys())
print(HCIA_AIdict.values())
print(HCIA_AIdict['Philip_Oyier'])
print('Philip_Oyier' in HCIA_AIdict)



dict_items([('Philip_Oyier', 'kisumu'), ('Peter_Kiguru', 'Kiambu'), ('Susan_Neema', 'Nairobi'), ('Mary_Njue', 'Kiambu'), ('Eddie_Chege', 'Kiambu')])
dict_keys(['Philip_Oyier', 'Peter_Kiguru', 'Susan_Neema', 'Mary_Njue', 'Eddie_Chege'])
dict_values(['kisumu', 'Kiambu', 'Nairobi', 'Kiambu', 'Kiambu'])
kisumu
True


In [52]:
s= "We are on course with HCIA-AI Certification"
print(s)

We are on course with HCIA-AI Certification


In [53]:
print(3*s)
print(s[1])
print(s[2])
print(s[::2])

We are on course with HCIA-AI CertificationWe are on course with HCIA-AI CertificationWe are on course with HCIA-AI Certification
e
 
W r ncus ihHI-ICriiain


In [54]:
text = "Huawei AI Bootcamp June 2025"
print(text.upper())
print(text.lower())
print(text.split())
print("+".join(text.split()))
print(text.replace('Comrades','Students'))
print(text.find('Students'))
print(text.count('n'))

HUAWEI AI BOOTCAMP JUNE 2025
huawei ai bootcamp june 2025
['Huawei', 'AI', 'Bootcamp', 'June', '2025']
Huawei+AI+Bootcamp+June+2025
Huawei AI Bootcamp June 2025
-1
1


In [55]:
for i in range(101):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [56]:
for i in range(1,101):
  if i%7==0:
    print(i)


7
14
21
28
35
42
49
56
63
70
77
84
91
98


In [57]:
for i in range(101):
  if i%5==0 and i%3!=0:
    print(i)

5
10
20
25
35
40
50
55
65
70
80
85
95
100


In [58]:
for x in range(2, 21):
    divisors = []
    for i in range(2, x):
        if x % i == 0:
            divisors.append(i)
    if divisors:
        print(f"For {x}, it should print: {' '.join(map(str, divisors))}")
    else:
       pass

For 4, it should print: 2
For 6, it should print: 2 3
For 8, it should print: 2 4
For 9, it should print: 3
For 10, it should print: 2 5
For 12, it should print: 2 3 4 6
For 14, it should print: 2 7
For 15, it should print: 3 5
For 16, it should print: 2 4 8
For 18, it should print: 2 3 6 9
For 20, it should print: 2 4 5 10


In [59]:
def Mul(num1,num2):
  return(num1*num2)

print(Mul(8,6))

48


In [60]:
def sqrProd(x,y):
  product = x*y
  return product*product

print(sqrProd(2,5))

100


In [63]:
import numpy as np
arrays_zero = np.zeros((5,5))
print(arrays_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [65]:
arr1 = np.arange(9).reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [67]:
arr2 = np.random.rand(10,10)
print(arr2)
min = arr2.min()
max = arr2.max()
print(min)
print(max)

[[0.815501   0.2154775  0.35448629 0.8493403  0.56012245 0.73819877
  0.5081768  0.15787985 0.22047448 0.42108206]
 [0.8637701  0.88681722 0.08991555 0.72717427 0.29468252 0.60901311
  0.01256422 0.84957136 0.64531695 0.13316703]
 [0.99696165 0.04711869 0.47041796 0.50731128 0.97105244 0.34447115
  0.51041004 0.47476733 0.02846512 0.50900058]
 [0.10306052 0.49897873 0.35007272 0.89559617 0.16578013 0.45852038
  0.19515713 0.04104245 0.52438408 0.62802352]
 [0.66738418 0.19717331 0.21472796 0.53539101 0.61554078 0.29439138
  0.41174799 0.93483022 0.60714652 0.46252094]
 [0.24245535 0.209304   0.65191735 0.46937053 0.96327755 0.34323781
  0.68487668 0.41885467 0.31197514 0.20451935]
 [0.63627445 0.20589698 0.26928275 0.92287082 0.33131817 0.82517328
  0.97390861 0.1550251  0.23013525 0.75596277]
 [0.80828188 0.32392908 0.32558374 0.45700624 0.80857018 0.75279263
  0.87029816 0.39075867 0.78948068 0.77906989]
 [0.0676671  0.38709931 0.78490995 0.16376989 0.94647498 0.94303444
  0.23310516

In [68]:
vec1 = np.random.rand(30)
mean_val = vec1.mean()
print(mean_val)

0.5042945868814507


In [69]:
prompt1 = input("Please enter the first number: ")
num1 = float(prompt1)
prompt2 = input("Please enter the second number: ")
num2 = float(prompt2)
print(num1*num2)



Please enter the first number: 2
Please enter the second number: 4
8.0


In [72]:
def doubleList(numberList):
  for number in numberList:
    print(number*2)
doubleList([3,1,5])

6
2
10


In [74]:
class Vehicle:
  def __init__(self, max_speed,mileage):
    self.max_speed = max_speed
    self.mileage = mileage

  def display_info(self):
    print(f"Max Speed: {self.max_speed} km/hr, Mileage: {self.mileage} km")


my_car = Vehicle(240, 10000)
my_car.display_info()

Max Speed: 240 km/hr, Mileage: 10000 km


In [75]:
class Bus(Vehicle):
    def __init__(self, name, max_speed, mileage):
        super().__init__(max_speed, mileage)
        self.name = name

    def display_info(self):
        print(f"Name: {self.name}, ", end="")
        super().display_info()

school_mercedes = Bus("School Mercedes", 180, 1000)
school_mercedes.display_info()

Name: School Mercedes, Max Speed: 180 km/hr, Mileage: 1000 km


In [77]:

class Bus(Vehicle):
    def __init__(self, name, max_speed, mileage, seating_capacity=50):
        super().__init__(max_speed, mileage)
        self.name = name
        self.seating_capacity = seating_capacity

    def display_info(self):
        print(f"Name: {self.name}, Max Speed: {self.max_speed} km/hr, Mileage: {self.mileage} km, Seating Capacity: {self.seating_capacity}")


bus_with_default_seats = Bus("City Express", 120, 5000)
bus_with_default_seats.display_info()


Name: City Express, Max Speed: 120 km/hr, Mileage: 5000 km, Seating Capacity: 50


In [78]:
class Vehicle:
    color = "White"

    def __init__(self, max_speed, mileage):
        self.max_speed = max_speed
        self.mileage = mileage

    def display_info(self):
        print(f"Color: {Vehicle.color}, Max Speed: {self.max_speed} km/hr, Mileage: {self.mileage} km")

class Bus(Vehicle):
    def __init__(self, name, max_speed, mileage, seating_capacity=50):
        super().__init__(max_speed, mileage)
        self.name = name
        self.seating_capacity = seating_capacity

    def display_info(self):
        print(f"Name: {self.name}, Color: {self.color}, Max Speed: {self.max_speed} km/hr, Mileage: {self.mileage} km, Seating Capacity: {self.seating_capacity}")

print("\nd) Vehicle and Bus Classes (with 'color' class attribute):")

my_other_car = Vehicle(200, 15000)
my_other_car.display_info()


school_bus_final = Bus("School Shuttle", 100, 2000, 40)
school_bus_final.display_info()




d) Vehicle and Bus Classes (with 'color' class attribute):
Color: White, Max Speed: 200 km/hr, Mileage: 15000 km
Name: School Shuttle, Color: White, Max Speed: 100 km/hr, Mileage: 2000 km, Seating Capacity: 40
